/***********************************************************************************
**
**	Copyright (C) 14.07.2021 Uwe Merker Germany
**
**	Diese Datei ist Teil von CPM_Image_File_Explorer.
**
**	CPM_Image_File_Explorer ist Freie Software: Sie können es unter den Bedingungen
**	der GNU General Public License, wie von der Free Software Foundation,
**	Version 3 der Lizenz oder (nach Ihrer Wahl) jeder späteren
**	veröffentlichten Version, weiterverbreiten und/oder modifizieren.
**
**	CPM_Image_File_Explorer wird in der Hoffnung, dass es nützlich sein wird, aber
**	OHNE JEDE GEWÄHRLEISTUNG, bereitgestellt; sogar ohne die implizite
**	Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
**	Siehe die GNU General Public License für weitere Details.
**
**	Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
**	Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>.
**
***********************************************************************************/

//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Ui_MainWindow.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CPM_IMAGE_FILE_EXPLORER_CIFE_UI_MAINWINDOW_BASE_CLASSES_H
#define _CPM_IMAGE_FILE_EXPLORER_CIFE_UI_MAINWINDOW_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#if wxVERSION_NUMBER >= 2900
    #include <wx/persist.h>
    #include <wx/persist/toplevel.h>
    #include <wx/persist/bookctrl.h>
    #include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
    #undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
    #define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
    #define WXC_FROM_DIP(x) x
#endif

// clang-format on

class Ui_MainWindow : public wxFrame {
    protected:

    protected:

    public:
        Ui_MainWindow(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString &title = _("CP/M Image File Explorer"), const wxPoint &pos = wxDefaultPosition, const wxSize &size = wxSize(500, 300), long style = wxDEFAULT_FRAME_STYLE);
        virtual ~Ui_MainWindow();
};

#endif
