//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Ui_MainWindow.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "Ui_MainWindow.h"


// Declare the bitmap loading function
extern void wxCrafterbA4dhxInitBitmapResources();

static bool bBitmapLoaded = false;


Ui_MainWindow::Ui_MainWindow(wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos, const wxSize &size, long style)
    : wxFrame(parent, id, title, pos, size, style) {
    if (!bBitmapLoaded) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafterbA4dhxInitBitmapResources();
        bBitmapLoaded = true;
    }

    menuMainWindow = new wxMenuBar(0);
    this->SetMenuBar(menuMainWindow);

    menuFile = new wxMenu();
    menuMainWindow->Append(menuFile, _("File"));

    menuItemClose = new wxMenuItem(menuFile, wxID_CLOSE, _("Close"), wxT(""), wxITEM_NORMAL);
    menuFile->Append(menuItemClose);

    menuHelp = new wxMenu();
    menuMainWindow->Append(menuHelp, _("Help"));

    menuItemAbout = new wxMenuItem(menuHelp, wxID_ABOUT, _("About ..."), wxT(""), wxITEM_NORMAL);
    menuHelp->Append(menuItemAbout);

    statusMainWindow = new wxStatusBar(this, wxID_ANY, wxSTB_DEFAULT_STYLE);
    statusMainWindow->SetFieldsCount(1);
    this->SetStatusBar(statusMainWindow);

    sizerMainWindow = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(sizerMainWindow);

    panelImageFile = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

    sizerMainWindow->Add(panelImageFile, 0, wxEXPAND, WXC_FROM_DIP(4));

    sizerImage = new wxGridBagSizer(0, 0);
    panelImageFile->SetSizer(sizerImage);

    textImageType = new wxStaticText(panelImageFile, wxID_ANY, _("Image Typ :"), wxDefaultPosition, wxDLG_UNIT(panelImageFile, wxSize(-1, -1)), 0);

    sizerImage->Add(textImageType, wxGBPosition(0, 0), wxGBSpan(1, 1), wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, WXC_FROM_DIP(4));

    sizerImageType = new wxBoxSizer(wxHORIZONTAL);

    sizerImage->Add(sizerImageType, wxGBPosition(0, 1), wxGBSpan(1, 1), wxTOP | wxBOTTOM, WXC_FROM_DIP(4));

    wxArrayString comboboxImageTypeArr;
    comboboxImageType = new wxComboBox(panelImageFile, wxID_IMAGE_TYPE, wxT(""), wxDefaultPosition, wxDLG_UNIT(panelImageFile, wxSize(-1, -1)), comboboxImageTypeArr, wxCB_READONLY);

    sizerImageType->Add(comboboxImageType, 0, 0, WXC_FROM_DIP(4));

    sizerImageType->Add(-1, -1, 0, 0, WXC_FROM_DIP(5));

    textImageFile = new wxStaticText(panelImageFile, wxID_ANY, _("Image Datei :"), wxDefaultPosition, wxDLG_UNIT(panelImageFile, wxSize(-1, -1)), 0);

    sizerImage->Add(textImageFile, wxGBPosition(1, 0), wxGBSpan(1, 1), wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, WXC_FROM_DIP(4));

    editImageFile = new wxTextCtrl(panelImageFile, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(panelImageFile, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
    editImageFile->SetHint(wxT(""));
#endif

    sizerImage->Add(editImageFile, wxGBPosition(1, 1), wxGBSpan(1, 1), wxRIGHT | wxEXPAND, WXC_FROM_DIP(2));

    buttonImageFile = new wxButton(panelImageFile, wxID_BUTTON_IMAGE_FILE, _("..."), wxDefaultPosition, wxDLG_UNIT(panelImageFile, wxSize(-1, -1)), 0);

    sizerImage->Add(buttonImageFile, wxGBPosition(1, 2), wxGBSpan(1, 1), wxRIGHT, WXC_FROM_DIP(4));
    sizerImage->AddGrowableCol(1);
    panelImageContents = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

    sizerMainWindow->Add(panelImageContents, 1, wxEXPAND, WXC_FROM_DIP(5));

    sizeImageContents = new wxBoxSizer(wxVERTICAL);
    panelImageContents->SetSizer(sizeImageContents);

    listImageContents = new wxListCtrl(panelImageContents, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(panelImageContents, wxSize(-1, -1)), wxLC_REPORT);

    sizeImageContents->Add(listImageContents, 1, wxLEFT | wxRIGHT | wxBOTTOM | wxEXPAND, WXC_FROM_DIP(4));

    SetName(wxT("Ui_MainWindow"));
    SetSize(wxDLG_UNIT(this, wxSize(500, 300)));

    if (GetSizer()) {
        GetSizer()->Fit(this);
    }

    if (GetParent()) {
        CentreOnParent(wxBOTH);
    }
    else {
        CentreOnScreen(wxBOTH);
    }
}

Ui_MainWindow::~Ui_MainWindow() {
}
