//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Ui_CreateFileDialog.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CIFE_GUI_DESIGNS_UI_CREATEFILEDIALOG_BASE_CLASSES_HPP
#define _CIFE_GUI_DESIGNS_UI_CREATEFILEDIALOG_BASE_CLASSES_HPP

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/gbsizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/checkbox.h>
#include <wx/panel.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class Ui_CreateFileDialog : public wxDialog
{
public:
    enum {
        wxID_BUTTON_BOOTFILE = 10001,
        wxID_BUTTON_IMAGEFILE = 10002,
    };
protected:
    wxStaticText* textImageFile;
    wxStaticText* textBootTrackFile;
    wxStaticText* textFileSystemLabel;
    wxTextCtrl* editFileSystemLabel;
    wxCheckBox* checkboxUseTimeStamps;
    wxPanel* panelImageFile;
    wxTextCtrl* editImageFile;
    wxButton* buttonImageFile;
    wxPanel* panelBootTrackFile;
    wxTextCtrl* editBootTrackFile;
    wxButton* buttonBootTrackFile;
    wxPanel* panelCreationWarning;
    wxStaticText* textWarning1;
    wxStaticText* textWarning2;
    wxButton* buttonCancel;
    wxButton* buttonOk;

protected:

public:
    wxStaticText* GetTextImageFile() { return textImageFile; }
    wxStaticText* GetTextBootTrackFile() { return textBootTrackFile; }
    wxStaticText* GetTextFileSystemLabel() { return textFileSystemLabel; }
    wxTextCtrl* GetEditFileSystemLabel() { return editFileSystemLabel; }
    wxCheckBox* GetCheckboxUseTimeStamps() { return checkboxUseTimeStamps; }
    wxTextCtrl* GetEditImageFile() { return editImageFile; }
    wxButton* GetButtonImageFile() { return buttonImageFile; }
    wxPanel* GetPanelImageFile() { return panelImageFile; }
    wxTextCtrl* GetEditBootTrackFile() { return editBootTrackFile; }
    wxButton* GetButtonBootTrackFile() { return buttonBootTrackFile; }
    wxPanel* GetPanelBootTrackFile() { return panelBootTrackFile; }
    wxStaticText* GetTextWarning1() { return textWarning1; }
    wxStaticText* GetTextWarning2() { return textWarning2; }
    wxPanel* GetPanelCreationWarning() { return panelCreationWarning; }
    wxButton* GetButtonCancel() { return buttonCancel; }
    wxButton* GetButtonOk() { return buttonOk; }
    Ui_CreateFileDialog(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Create new empty Image-File"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~Ui_CreateFileDialog();
};

#endif
