//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Ui_FileProtectionsDialog.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CPM_IMAGE_FILE_EXPLORER_CIFE_UI_FILEPROTECTIONSDIALOG_BASE_CLASSES_H
#define _CPM_IMAGE_FILE_EXPLORER_CIFE_UI_FILEPROTECTIONSDIALOG_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/checkbox.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
    #include <wx/persist.h>
    #include <wx/persist/toplevel.h>
    #include <wx/persist/bookctrl.h>
    #include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
    #undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
    #define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
    #define WXC_FROM_DIP(x) x
#endif

// clang-format on

class Ui_FileProtectionsDialog : public wxDialog {
    public:
        enum {
            wxID_DELETE_PROTECT = 10001,
            wxID_WRITE_PROTECT = 10002,
            wxID_READ_PROTECT = 10003,
        };
    protected:
        wxBoxSizer *sizerFileProtectionsDialog;
        wxPanel *panelFileProtections;
        wxBoxSizer *sizerFileProtections;
        wxCheckBox *checkboxReadProtect;
        wxCheckBox *checkboxWriteProtect;
        wxCheckBox *checkboxDeleteProtect;
        wxPanel *panelDialogButtons;
        wxBoxSizer *sizerDialogButtons;
        wxButton *buttonCancel;
        wxButton *buttonOk;

    protected:

    public:
        wxCheckBox *GetCheckboxReadProtect() {
            return checkboxReadProtect;
        }
        wxCheckBox *GetCheckboxWriteProtect() {
            return checkboxWriteProtect;
        }
        wxCheckBox *GetCheckboxDeleteProtect() {
            return checkboxDeleteProtect;
        }
        wxPanel *GetPanelFileProtections() {
            return panelFileProtections;
        }
        wxButton *GetButtonCancel() {
            return buttonCancel;
        }
        wxButton *GetButtonOk() {
            return buttonOk;
        }
        wxPanel *GetPanelDialogButtons() {
            return panelDialogButtons;
        }
        Ui_FileProtectionsDialog(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString &title = _("File Protections"), const wxPoint &pos = wxDefaultPosition, const wxSize &size = wxSize(-1, -1), long style = wxDEFAULT_DIALOG_STYLE);
        virtual ~Ui_FileProtectionsDialog();
};

#endif
