//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Ui_FileCopySettingsDialog.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CIFE_GUI_DESIGNS_UI_FILECOPYSETTINGSDIALOG_BASE_CLASSES_HPP
#define _CIFE_GUI_DESIGNS_UI_FILECOPYSETTINGSDIALOG_BASE_CLASSES_HPP

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/spinctrl.h>
#include <wx/checkbox.h>
#include <wx/textctrl.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class Ui_FileCopySettingsDialog : public wxDialog
{
protected:
    wxPanel* panelDefaultUserNumber;
    wxStaticText* textDefaultUserNumber;
    wxSpinCtrl* spinCtrlDefaultUserNumber;
    wxPanel* panelKeepLastUpdated;
    wxCheckBox* checkboxKeepLastUpdated;
    wxPanel* panelTextfileEndings;
    wxStaticText* labelTextFileEndings;
    wxTextCtrl* editTextFileEndings;

protected:

public:
    wxStaticText* GetTextDefaultUserNumber() { return textDefaultUserNumber; }
    wxSpinCtrl* GetSpinCtrlDefaultUserNumber() { return spinCtrlDefaultUserNumber; }
    wxPanel* GetPanelDefaultUserNumber() { return panelDefaultUserNumber; }
    wxCheckBox* GetCheckboxKeepLastUpdated() { return checkboxKeepLastUpdated; }
    wxPanel* GetPanelKeepLastUpdated() { return panelKeepLastUpdated; }
    wxStaticText* GetLabelTextFileEndings() { return labelTextFileEndings; }
    wxTextCtrl* GetEditTextFileEndings() { return editTextFileEndings; }
    wxPanel* GetPanelTextfileEndings() { return panelTextfileEndings; }
    Ui_FileCopySettingsDialog(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("File Copy Settings"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxBORDER_THEME);
    virtual ~Ui_FileCopySettingsDialog();
};

#endif
