//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Ui_GeneralSettingsDialog.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CIFE_GUI_DESIGNS_UI_GENERALSETTINGSDIALOG_BASE_CLASSES_HPP
#define _CIFE_GUI_DESIGNS_UI_GENERALSETTINGSDIALOG_BASE_CLASSES_HPP

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/checkbox.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class Ui_GeneralSettingsDialog : public wxDialog
{
protected:
    wxPanel* panelCifeStartupSettings;
    wxCheckBox* checkboxOpenLastImage;
    wxPanel* panelCpmFileSystemSettings;
    wxCheckBox* checkboxUseCpmUppercase;

protected:

public:
    wxCheckBox* GetCheckboxOpenLastImage() { return checkboxOpenLastImage; }
    wxPanel* GetPanelCifeStartupSettings() { return panelCifeStartupSettings; }
    wxCheckBox* GetCheckboxUseCpmUppercase() { return checkboxUseCpmUppercase; }
    wxPanel* GetPanelCpmFileSystemSettings() { return panelCpmFileSystemSettings; }
    Ui_GeneralSettingsDialog(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("General Settings"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~Ui_GeneralSettingsDialog();
};

#endif
