//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Ui_GeneralSettingsDialog.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "Ui_GeneralSettingsDialog.hpp"


// Declare the bitmap loading function
extern void wxCrafter0ioYfZInitBitmapResources();

static bool bBitmapLoaded = false;


Ui_GeneralSettingsDialog::Ui_GeneralSettingsDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafter0ioYfZInitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* sizerGeneralSettingsDialog = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(sizerGeneralSettingsDialog);
    
    panelCifeStartupSettings = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL|wxBORDER_THEME);
    
    sizerGeneralSettingsDialog->Add(panelCifeStartupSettings, 0, wxALL, WXC_FROM_DIP(4));
    
    wxBoxSizer* sizerCifeStartupSettings = new wxBoxSizer(wxVERTICAL);
    panelCifeStartupSettings->SetSizer(sizerCifeStartupSettings);
    
    checkboxOpenLastImage = new wxCheckBox(panelCifeStartupSettings, wxID_ANY, _("open last Image on next Startup"), wxDefaultPosition, wxDLG_UNIT(panelCifeStartupSettings, wxSize(-1,-1)), 0);
    checkboxOpenLastImage->SetValue(false);
    
    sizerCifeStartupSettings->Add(checkboxOpenLastImage, 0, wxALL, WXC_FROM_DIP(5));
    
    panelCpmFileSystemSettings = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL|wxBORDER_THEME);
    
    sizerGeneralSettingsDialog->Add(panelCpmFileSystemSettings, 0, wxALL, WXC_FROM_DIP(4));
    
    wxBoxSizer* sizerCpmFileSystemSettings = new wxBoxSizer(wxVERTICAL);
    panelCpmFileSystemSettings->SetSizer(sizerCpmFileSystemSettings);
    
    checkboxUseCpmUppercase = new wxCheckBox(panelCpmFileSystemSettings, wxID_ANY, _("use uppercase characters in CP/M filesystem"), wxDefaultPosition, wxDLG_UNIT(panelCpmFileSystemSettings, wxSize(-1,-1)), 0);
    checkboxUseCpmUppercase->SetValue(false);
    
    sizerCpmFileSystemSettings->Add(checkboxUseCpmUppercase, 0, wxALL, WXC_FROM_DIP(5));
    
    SetName(wxT("Ui_GeneralSettingsDialog"));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
}

Ui_GeneralSettingsDialog::~Ui_GeneralSettingsDialog()
{
}
